feat: add tag function
ALPGO-AI/ui-admin pull request #57
Opened 2023-05-16 03:40 UTC by Swimcat

2023-05-16 05:32 UTC, AsahiLuna requested changes
去掉无用代码，修复code style问题

2023-05-16 05:32 UTC, AsahiLuna commented on alpgo-system/src/main/java/cc/alpgo/tag/config/config.java
> +public class config {
无用代码，可以删掉

2023-05-16 05:32 UTC, AsahiLuna commented on alpgo-system/src/main/java/cc/alpgo/tag/domain/CommonTag.java
> + public class   CommonTag extends BaseEntity
注意code style，空格多了

2023-05-16 06:54 UTC, Swimcat commented on alpgo-system/src/main/java/cc/alpgo/tag/domain/CommonTag.java
> + public class   CommonTag extends BaseEntity
好的

2023-05-18 00:25 UTC, AsahiLuna approved these changes

2023-05-18 00:25 UTC, AsahiLuna approved these changes

2023-05-18 00:25 UTC, merged